#!/bin/bash

# Help information
description="Remove the shared memory keys generated by SAL."
usageMsg="Usage: `basename $0` [CSC Name]"
if [[ "$1" = "--help" ]]; then
    echo ${description}
    echo ${usageMsg}
    exit 0
fi

if [[ $# = 0 ]]; then
    echo ${usageMsg}
    exit 0
fi

# Iterate the input CSCs to remove the shared memory
for csc in "$@"
do
    # Get the memory address
    md5CheckSum="$(echo "$csc" | md5sum)"
    memAddr="0x0000${md5CheckSum:0:4}"

    # Remove the shared memory id
    {
        ipcrm --shmem-key ${memAddr}
    } || {
        echo "No memory key of CSC: ${csc}."
    }
done
