#!/bin/bash

# Help information
description="Remove the shared memory key generated by SAL."
usageMsg="Usage: `basename $0` cscName [--index] [index]"
if [ "$1" = "--help" ]; then
    echo ${description}
    echo ${usageMsg}
    exit 0
fi

# Check the number of input arguments
if [ $# -eq 0 ] || [ $# -eq 2 ] || [ $# -gt 3 ]; then
    echo ${usageMsg}
    exit 0
fi

# Assign the variables from inputs
csc="$1"
index=0
if [ $# -eq 3 ]; then
    if [ $2 == "--index" ]; then
        index=$3
    else
        echo ${usageMsg}
        exit 0
    fi
fi

# Get the memory address of CSC
md5CheckSum="$(echo "${csc}" | md5sum)"
addr=`printf "%X\n" $((0x${md5CheckSum:0:4}+0x${index}))`
memAddr="0x0000${addr}"

# Remove the shared memory id
{
    ipcrm --shmem-key ${memAddr}
} || {
    echo "No memory key of CSC: ${csc}. Index is ${index}."
}
